import { useState } from 'react';
import { useWorkflowStore } from '../../../store/workflowStore';
import { Braces } from 'lucide-react';

export default function VariablePicker({ 
  onSelect, 
  formatAs = 'template',
  currentSequence
}: { 
  onSelect: (variable: string) => void;
  formatAs?: 'template' | 'js';
  currentSequence?: number;
}) {
  const [isOpen, setIsOpen] = useState(false);
  let actions = useWorkflowStore(s => s.actions);

  if (typeof currentSequence === 'number') {
    actions = actions.filter(a => a.sequence < currentSequence);
  }

  const formatVar = (path: string) => {
    if (formatAs === 'js') {
      // e.g. trigger.body -> trigger.body
      // e.g. steps.0.http_response -> steps['0'].http_response
      const parts = path.split('.');
      if (parts[0] === 'steps') {
        return `steps['${parts[1]}']${parts.length > 2 ? '.' + parts.slice(2).join('.') : ''}`;
      }
      return path;
    }
    return `{{${path}}}`;
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className="text-xs flex items-center gap-1 text-blue-400 hover:text-blue-300 transition-colors mt-1"
        type="button"
      >
        <Braces className="w-3 h-3" />
        Insert Variable
      </button>
    );
  }

  const VarButton = ({ path, description }: { path: string, description: string }) => (
    <button 
      type="button" 
      onClick={() => onSelect(formatVar(path))} 
      className="block w-full text-left px-2 py-1.5 hover:bg-white/10 rounded transition-colors group mb-1"
    >
      <div className="text-xs text-blue-400 font-mono group-hover:text-blue-300">{formatVar(path)}</div>
      <div className="text-[10px] text-white/50 mt-0.5 leading-tight">{description}</div>
    </button>
  );

  return (
    <div className="mt-2 p-3 bg-black/40 border border-surface-border rounded-lg text-sm">
      <div className="flex justify-between items-center mb-2 text-white/50 text-xs font-semibold uppercase">
        Available Variables
        <button onClick={() => setIsOpen(false)} className="hover:text-white" type="button">Close</button>
      </div>
      
      <div className="space-y-4 max-h-[300px] overflow-y-auto pr-1">
        {/* Trigger Variables */}
        <div>
          <div className="text-white/80 font-medium mb-1.5 text-xs">Trigger</div>
          <VarButton 
            path="trigger.body" 
            description="The JSON payload that triggered this workflow"
          />
        </div>

        {/* Previous Action Variables */}
        {actions.map(a => (
          <div key={a.id}>
            <div className="text-white/80 font-medium mb-1.5 text-xs">Step {a.sequence}: {a.actionType.replace(/_/g, ' ')}</div>
            
            {a.actionType === 'HTTP_REQUEST' && (
              <>
                <VarButton path={`steps.${a.sequence}.http_response`} description="The parsed JSON data returned by the API" />
                <VarButton path={`steps.${a.sequence}.status`} description="The HTTP status code (e.g., 200, 404)" />
              </>
            )}
            
            {(a.actionType === 'CUSTOM_CODE' || a.actionType === 'AI_ANALYZE') && (
              <VarButton path={`steps.${a.sequence}.result`} description="The resulting text or data generated by this step" />
            )}

            {a.actionType === 'SAVE_TO_DB' && (
              <VarButton path={`steps.${a.sequence}.savedId`} description="The unique ID of the inserted database record" />
            )}

            {a.actionType === 'SEND_EMAIL' && (
              <>
                <VarButton path={`steps.${a.sequence}.message`} description="Success message from the email provider" />
                <VarButton path={`steps.${a.sequence}.id`} description="The delivery tracking ID of the sent email" />
              </>
            )}

            {a.actionType === 'CONDITION' && (
              <VarButton path={`steps.${a.sequence}.met`} description="True if the condition evaluated to true, otherwise false" />
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
