import { useState, useEffect } from 'react';
import { useWorkflowStore } from '../../../store/workflowStore';
import { useAuthStore } from '../../../store/authStore';
import { getSecretsApi } from '../../../services/secret';
import { Braces, KeyRound } from 'lucide-react';

export default function VariablePicker({ 
  onSelect, 
  formatAs = 'template',
  currentSequence
}: { 
  onSelect: (variable: string) => void;
  formatAs?: 'template' | 'js';
  currentSequence?: number;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [secrets, setSecrets] = useState<any[]>([]);
  const activeWorkspaceId = useAuthStore(s => s.activeWorkspaceId);
  let actions = useWorkflowStore(s => s.actions);

  useEffect(() => {
    if (isOpen && activeWorkspaceId) {
      getSecretsApi(activeWorkspaceId)
        .then(res => setSecrets(res.data))
        .catch(console.error);
    }
  }, [isOpen, activeWorkspaceId]);

  if (typeof currentSequence === 'number') {
    actions = actions.filter(a => a.sequence < currentSequence);
  }

  const formatVar = (path: string) => {
    if (formatAs === 'js') {
      const parts = path.split('.');
      if (parts[0] === 'steps') {
        return `steps['${parts[1]}']${parts.length > 2 ? '.' + parts.slice(2).join('.') : ''}`;
      }
      return path;
    }
    return `{{${path}}}`;
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className="text-xs flex items-center gap-1 text-primary hover:text-primary-hover transition-colors mt-1 font-medium"
        type="button"
      >
        <Braces className="w-3 h-3" />
        Insert Variable
      </button>
    );
  }

  const VarButton = ({ path, description }: { path: string, description: string }) => (
    <button 
      type="button" 
      onClick={() => { onSelect(formatVar(path)); setIsOpen(false); }} 
      className="block w-full text-left px-2 py-1.5 hover:bg-surface-border rounded transition-colors group"
    >
      <div className="text-xs text-primary font-mono group-hover:text-primary-hover">{formatVar(path)}</div>
      <div className="text-[10px] text-muted mt-0.5 leading-tight">{description}</div>
    </button>
  );

  return (
    <div className="mt-2 p-3 bg-surface border border-surface-border rounded-lg text-sm shadow-sm">
      <div className="flex justify-between items-center mb-2 text-foreground/50 text-xs font-semibold uppercase">
        Available Variables
        <button onClick={() => setIsOpen(false)} className="hover:text-foreground" type="button">Close</button>
      </div>
      
      <div className="space-y-4 max-h-[300px] overflow-y-auto pr-1">
        {/* Trigger Variables */}
        <div>
          <div className="text-foreground font-medium mb-1.5 text-xs">Trigger</div>
          <VarButton 
            path="trigger.body" 
            description="The JSON payload that triggered this workflow"
          />
        </div>

        {/* Secrets */}
        {secrets.length > 0 && (
          <div>
            <div className="text-foreground font-medium mb-1.5 text-xs flex items-center gap-1 mt-3">
              <KeyRound className="w-3 h-3 text-orange-500" /> Workspace Secrets
            </div>
            {secrets.map(s => (
              <VarButton 
                key={s.id}
                path={`secrets.${s.name}`} 
                description={s.description || 'Workspace level secret key'}
              />
            ))}
          </div>
        )}

        {/* Previous Action Variables */}
        {actions.map(a => (
          <div key={a.id}>
            <div className="text-foreground font-medium mb-1.5 text-xs">Step {a.sequence}: {a.actionType.replace(/_/g, ' ')}</div>
            
            {a.actionType === 'HTTP_REQUEST' && (
              <>
                <VarButton path={`steps.${a.sequence}.http_response`} description="The parsed JSON data returned by the API" />
                <VarButton path={`steps.${a.sequence}.status`} description="The HTTP status code (e.g., 200, 404)" />
              </>
            )}
            
            {(a.actionType === 'CUSTOM_CODE' || a.actionType === 'AI_ANALYZE') && (
              <VarButton path={`steps.${a.sequence}.result`} description="The resulting text or data generated by this step" />
            )}

            {a.actionType === 'SAVE_TO_DB' && (
              <VarButton path={`steps.${a.sequence}.savedId`} description="The unique ID of the inserted database record" />
            )}

            {a.actionType === 'SEND_EMAIL' && (
              <>
                <VarButton path={`steps.${a.sequence}.message`} description="Success message from the email provider" />
                <VarButton path={`steps.${a.sequence}.id`} description="The delivery tracking ID of the sent email" />
              </>
            )}

            {a.actionType === 'CONDITION' && (
              <VarButton path={`steps.${a.sequence}.met`} description="True if the condition evaluated to true, otherwise false" />
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
